[ 2019-08-21T23:02:56+08:00 ] 127.0.0.1 127.0.0.1 GET /banner/1
[ log ] z.cn/banner/1 [运行时间：0.033391s][吞吐率：29.95req/s] [内存消耗：1,144.63kb] [文件加载：34]
[ error ] [1]Uncaught think\exception\ErrorException: Declaration of app\lib\exception\ExceptionHandler::render(think\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10
Stack trace:
#0 /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php(10): think\Error::appError(2, 'Declaration of ...', '/Users/nirvana/...', 10, Array)
#1 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(562): include('/Users/nirvana/...')
#2 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(58): think\__include_file('/Users/nirvana/...')
#3 [internal function]: think\Loader::autoload('app\\lib\\excepti...')
#4 [internal function]: spl_autoload_call('app\\lib\\excepti...')
#5 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(109): class_exists('app\\lib\\excepti...')
#6 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(43): think\Error::getExceptionHandler()
#7 [internal function[/Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10]
[ error ] Uncaught think\exception\ErrorException: Declaration of app\lib\exception\ExceptionHandler::render(think\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10
Stack trace:
#0 /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php(10): think\Error::appError(2, 'Declaration of ...', '/Users/nirvana/...', 10, Array)
#1 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(562): include('/Users/nirvana/...')
#2 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(58): think\__include_file('/Users/nirvana/...')
#3 [internal function]: think\Loader::autoload('app\\lib\\excepti...')
#4 [internal function]: spl_autoload_call('app\\lib\\excepti...')
#5 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(109): class_exists('app\\lib\\excepti...')
#6 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(43): think\Error::getExceptionHandler()
#7 [internal function

---------------------------------------------------------------
[ 2019-08-21T23:05:26+08:00 ] 127.0.0.1 127.0.0.1 GET /banner/1
[ log ] z.cn/banner/1 [运行时间：0.035553s][吞吐率：28.13req/s] [内存消耗：1,144.78kb] [文件加载：34]
[ error ] [1]Uncaught think\exception\ErrorException: Declaration of app\lib\exception\ExceptionHandler::render(think\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10
Stack trace:
#0 /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php(10): think\Error::appError(2, 'Declaration of ...', '/Users/nirvana/...', 10, Array)
#1 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(562): include('/Users/nirvana/...')
#2 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(58): think\__include_file('/Users/nirvana/...')
#3 [internal function]: think\Loader::autoload('app\\lib\\excepti...')
#4 [internal function]: spl_autoload_call('app\\lib\\excepti...')
#5 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(109): class_exists('app\\lib\\excepti...')
#6 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(43): think\Error::getExceptionHandler()
#7 [internal function[/Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10]
[ error ] Uncaught think\exception\ErrorException: Declaration of app\lib\exception\ExceptionHandler::render(think\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10
Stack trace:
#0 /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php(10): think\Error::appError(2, 'Declaration of ...', '/Users/nirvana/...', 10, Array)
#1 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(562): include('/Users/nirvana/...')
#2 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(58): think\__include_file('/Users/nirvana/...')
#3 [internal function]: think\Loader::autoload('app\\lib\\excepti...')
#4 [internal function]: spl_autoload_call('app\\lib\\excepti...')
#5 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(109): class_exists('app\\lib\\excepti...')
#6 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(43): think\Error::getExceptionHandler()
#7 [internal function

---------------------------------------------------------------
[ 2019-08-21T23:06:09+08:00 ] 127.0.0.1 127.0.0.1 GET /banner/1
[ log ] z.cn/banner/1 [运行时间：0.038956s][吞吐率：25.67req/s] [内存消耗：1,144.90kb] [文件加载：34]
[ error ] [1]Uncaught think\exception\ErrorException: Declaration of app\lib\exception\ExceptionHandler::render(think\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10
Stack trace:
#0 /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php(10): think\Error::appError(2, 'Declaration of ...', '/Users/nirvana/...', 10, Array)
#1 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(562): include('/Users/nirvana/...')
#2 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(58): think\__include_file('/Users/nirvana/...')
#3 [internal function]: think\Loader::autoload('app\\lib\\excepti...')
#4 [internal function]: spl_autoload_call('app\\lib\\excepti...')
#5 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(109): class_exists('app\\lib\\excepti...')
#6 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(43): think\Error::getExceptionHandler()
#7 [internal function[/Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10]
[ error ] Uncaught think\exception\ErrorException: Declaration of app\lib\exception\ExceptionHandler::render(think\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10
Stack trace:
#0 /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php(10): think\Error::appError(2, 'Declaration of ...', '/Users/nirvana/...', 10, Array)
#1 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(562): include('/Users/nirvana/...')
#2 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(58): think\__include_file('/Users/nirvana/...')
#3 [internal function]: think\Loader::autoload('app\\lib\\excepti...')
#4 [internal function]: spl_autoload_call('app\\lib\\excepti...')
#5 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(109): class_exists('app\\lib\\excepti...')
#6 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(43): think\Error::getExceptionHandler()
#7 [internal function

---------------------------------------------------------------
[ 2019-08-21T23:06:32+08:00 ] 127.0.0.1 127.0.0.1 GET /banner/1
[ log ] z.cn/banner/1 [运行时间：0.031610s][吞吐率：31.64req/s] [内存消耗：1,144.90kb] [文件加载：34]
[ error ] [1]Uncaught think\exception\ErrorException: Declaration of app\lib\exception\ExceptionHandler::render(think\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10
Stack trace:
#0 /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php(10): think\Error::appError(2, 'Declaration of ...', '/Users/nirvana/...', 10, Array)
#1 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(562): include('/Users/nirvana/...')
#2 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(58): think\__include_file('/Users/nirvana/...')
#3 [internal function]: think\Loader::autoload('app\\lib\\excepti...')
#4 [internal function]: spl_autoload_call('app\\lib\\excepti...')
#5 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(109): class_exists('app\\lib\\excepti...')
#6 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(43): think\Error::getExceptionHandler()
#7 [internal function[/Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10]
[ error ] Uncaught think\exception\ErrorException: Declaration of app\lib\exception\ExceptionHandler::render(think\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10
Stack trace:
#0 /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php(10): think\Error::appError(2, 'Declaration of ...', '/Users/nirvana/...', 10, Array)
#1 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(562): include('/Users/nirvana/...')
#2 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(58): think\__include_file('/Users/nirvana/...')
#3 [internal function]: think\Loader::autoload('app\\lib\\excepti...')
#4 [internal function]: spl_autoload_call('app\\lib\\excepti...')
#5 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(109): class_exists('app\\lib\\excepti...')
#6 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(43): think\Error::getExceptionHandler()
#7 [internal function

---------------------------------------------------------------
[ 2019-08-21T23:16:20+08:00 ] 127.0.0.1 127.0.0.1 GET /banner/1
[ log ] z.cn/banner/1 [运行时间：0.077612s][吞吐率：12.88req/s] [内存消耗：1,155.58kb] [文件加载：36]
[ info ] [ LANG ] /Users/nirvana/Coding/zerg/thinkphp/lang/zh-cn.php
[ info ] [ ROUTE ] array (
  'type' => 'module',
  'module' => 
  array (
    0 => 'api',
    1 => 'v1.Banner',
    2 => 'getBanner',
  ),
  'convert' => false,
)
[ info ] [ HEADER ] array (
  'user-agent' => 'PostmanRuntime/7.15.2',
  'accept' => '*/*',
  'cache-control' => 'no-cache',
  'postman-token' => '4002aaca-7e64-48a8-b087-36c7bf888ead',
  'host' => 'z.cn',
  'accept-encoding' => 'gzip, deflate',
  'connection' => 'keep-alive',
)
[ info ] [ PARAM ] array (
  'id' => '1',
)
[ info ] [ RUN ] app\api\controller\v1\Banner->getBanner[ /Users/nirvana/Coding/zerg/application/api/controller/v1/Banner.php ]
[ info ] [ LOG ] INIT File
[ error ] [1]Uncaught think\exception\ErrorException: Declaration of app\lib\exception\ExceptionHandler::render(think\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10
Stack trace:
#0 /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php(10): think\Error::appError(2, 'Declaration of ...', '/Users/nirvana/...', 10, Array)
#1 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(562): include('/Users/nirvana/...')
#2 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(58): think\__include_file('/Users/nirvana/...')
#3 [internal function]: think\Loader::autoload('app\\lib\\excepti...')
#4 [internal function]: spl_autoload_call('app\\lib\\excepti...')
#5 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(109): class_exists('app\\lib\\excepti...')
#6 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(43): think\Error::getExceptionHandler()
#7 [internal function[/Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10]

---------------------------------------------------------------
[ 2019-08-21T23:16:49+08:00 ] [ error ] [1]Uncaught think\exception\ErrorException: Declaration of app\lib\exception\ExceptionHandler::render(think\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10
Stack trace:
#0 /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php(10): think\Error::appError(2, 'Declaration of ...', '/Users/nirvana/...', 10, Array)
#1 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(562): include('/Users/nirvana/...')
#2 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(58): think\__include_file('/Users/nirvana/...')
#3 [internal function]: think\Loader::autoload('app\\lib\\excepti...')
#4 [internal function]: spl_autoload_call('app\\lib\\excepti...')
#5 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(109): class_exists('app\\lib\\excepti...')
#6 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(43): think\Error::getExceptionHandler()
#7 [internal function
[ error ] Uncaught think\exception\ErrorException: Declaration of app\lib\exception\ExceptionHandler::render(think\Exception $e) should be compatible with think\exception\Handle::render(Exception $e) in /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php:10
Stack trace:
#0 /Users/nirvana/Coding/zerg/application/lib/exception/ExceptionHandler.php(10): think\Error::appError(2, 'Declaration of ...', '/Users/nirvana/...', 10, Array)
#1 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(562): include('/Users/nirvana/...')
#2 /Users/nirvana/Coding/zerg/thinkphp/library/think/Loader.php(58): think\__include_file('/Users/nirvana/...')
#3 [internal function]: think\Loader::autoload('app\\lib\\excepti...')
#4 [internal function]: spl_autoload_call('app\\lib\\excepti...')
#5 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(109): class_exists('app\\lib\\excepti...')
#6 /Users/nirvana/Coding/zerg/thinkphp/library/think/Error.php(43): think\Error::getExceptionHandler()
#7 [internal function

---------------------------------------------------------------
